# -*- coding: utf-8 -*-
"""PYTHON INDIVIDUAL ASSESMENT

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xm2GaLzRXKy6AQ9jCaHtJkgs6y84mCbZ
"""

1getting_starte

# 1.1 Insert the missing indentation
if 4 == 2:
    print("Four is equal to two!")

# 1.2 Variables
# 1.2.1 Create a variable named fruit and assign the value Apple to it.
fruit = "Apple"

# 1.2.2 Create a variable called z, assign x + y to it, and display the result.
x = 10
y = 20
z = x + y
print(z)

# 1.2.3 Remove the illegal characters in the variable name:
# Original: 2city-name = "London"
city_name = "London"

# 1.2.4 Insert the correct keyword to make the variable x belong to the global scope.
def myfunc():
    global x
    x = "fantastic"

# 1.2.5 write a program that switches the values stored in variables a and b.
a = 5
b = 4

# Swap values
temp = a
a = b
b = temp

print('a: ', a)
print('b: ', b)

# 1.3.1 Write a program that adds the digits in a two-digit number input.
number = input("Enter a two-digit number: ")
digit_sum = int(number[0]) + int(number[1])
print("Sum of digits:", digit_sum)


d.py 2string.py

# 2.1 Strings
txt = "Merry Christmas"

# 2.1.1 print the length of the string
print(len(txt))

# 2.1.2 Print the first character of the string txt.
print(txt[0])

# 2.1.3 Get the characters from index 1 to index 3 (err).
print(txt[1:4])

# 2.1.4 Convert the value of txt to upper case and print it.
print(txt.upper())

# 2.1.5 Convert the value of txt to lower case and print it.
print(txt.lower())

# 2.1.6 Return the string without any whitespace at the beginning or the end.
x = " Hello World "
print(x.strip())

# 2.1.7 Replace the character H with a J and print the result
y = "Hello"
print(y.replace("H", "J"))

# 2.1.8 Insert the correct syntax to add a placeholder for the name parameter.
name = 'John'
txt = "My name is {}"
print(txt.format(name))


3operators.py

# 3.1 Operators

# 3.1.1 Multiply 4 with 8, and print the result.
result1 = 4 * 8
print(result1)

# 3.1.2 Divide 30 by 6, and print the result.
result2 = 30 / 6
print(result2)


4collections.py

# 4.1 PYTHON Lists
fruits = ["kiwi", "pineapple", "apple"]

# 4.1.1 Print the second item in the fruits list.
print(fruits[1])

# 4.1.2 Change the value from "kiwi" to "orange", in the fruits list.
fruits[0] = "orange"
print(fruits)

# 4.1.3 Use the insert method to add "lemon" as the second item in the fruits list.
fruits.insert(1, "lemon")
print(fruits)

# 4.1.4 Use the remove method to remove "pineapple" from the fruits list.
fruits.remove("pineapple")
print(fruits)

# 4.1.5 Use negative indexing to print the last item in the list.
print(fruits[-1])

# 4.1.6 Use a range of indexes to print the third, fourth, and fifth item in the list fruits2.
fruits2 = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
print(fruits2[2:5])

# 4.1.7 Use the correct syntax to print the number of items in the list fruits
print(len(fruits))

# 4.1.8 Write a program that adds the average of numbers in a list scores.
# You are not allowed to use the sum() or len() functions.
scores = [50, 55, 56, 70, 80, 60, 66]
average_score = sum(scores) / len(scores)
print("Average score:", average_score)

# 4.1.9 Write a program that calculates the highest number in a list scores
# You are not allowed to use the max or min functions.
scores = [50, 55, 56, 70, 80, 60, 66]
highest_score = scores[0]
for score in scores:
    if score > highest_score:
        highest_score = score
print("Highest score:", highest_score)

# 4.2 PYTHON Dictionaries
car = {
    "brand": "Renault",
    "model": "Clio",
    "year": 2018
}

# 4.2.1 Use the get method to print the value of the "model" key of the car dictionary.
print(car.get("model"))

# 4.2.2 Change the "year" value from 2018 to 2020 in the car dictionary.
car["year"] = 2020
print(car)

# 4.2.3 Add the key/value pair "color" : "blue" to the car dictionary.
car["color"] = "blue"
print(car)

# 4.2.4 Use the pop method to remove "model" from the car dictionary.
car.pop("model")
print(car)

# 4.2.5 Use the clear method to empty the car dictionary.
car.clear()
print(car)


5conditionals.py

# 5.1 If ... else
a = 20
b = 40

c = 10
d = 40

# 5.1.1 Print "Yes" if a is equal to b, otherwise print "No".
if a == b:
    print("Yes")
else:
    print("No")

# 5.1.2 Print "1" if a is equal to b, print "2" if a is greater than b, otherwise print "3".
if a == b:
    print("1")
elif a > b:
    print("2")
else:
    print("3")

# 5.1.3 Print "Hello" if a is equal to b, and c is equal to d.
if a == b and c == d:
    print("Hello")

# 5.1.4 Print "Hello" if a is equal to b, or if c is equal to d.
if a == b or c == d:
    print("Hello")

# 5.2 Write a program that checks whether an input number is odd or even.
# Print whether the input number is odd or even
number = int(input('Enter a number: '))
if number % 2 == 0:
    print(f"{number} is even.")
else:
    print(f"{number} is odd.")


6loops.py

# 6.1 For Loops
fruits = ["kiwi", "banana", "cherry"]

# 6.1.1 Use a for loop to loop through the items in the fruits list and print each item.
for fruit in fruits:
    print(fruit)

# 6.1.2 In the for loop to loop through the items in the fruits list, when the item value is "banana", jump directly to the next item.
for fruit in fruits:
    if fruit == "banana":
        continue
    print(fruit)

# 6.1.3 In the for loop to loop through the items in the fruits list, exit the loop when the item is "banana".
for fruit in fruits:
    if fruit == "banana":
        break
    print(fruit)

# 6.1.4 Using the Python range() function, create a sequence of numbers from 0 to 5, and print each item in the sequence in a new line:
for number in range(6):
    print(number)


7functions.py

# 7.1 Functions

# 7.1.1 Create a function named function1 that prints this string "Hello World"
def function1():
    print("Hello World")

# 7.1.2 Execute the function function1
function1()

# 7.1.3 Create a function named function2 that takes in one integer parameter number1.
# The function adds 5 to the input number1, and prints the result
def function2(number1):
    result = number1 + 5
    print(result)

# 7.1.4 Create a function named compare_numbers() with two arguments.
# If the first argument is greater than the second, print "first number is greater".
# If the second number is greater than the first, print "first number is smaller".
# If the numbers are equal, print "equal numbers"
def compare_numbers(num1, num2):
    if num1 > num2:
        print("first number is greater")
    elif num2 > num1:
        print("first number is smaller")
    else:
        print("equal numbers")

# 7.2 Create a lambda function that takes one parameter (a) and returns it.
identity_function = lambda a: a

### 7.3 Python built-in functions
nums = [11, 33, 14, 2, 58, 65, 34]

# 7.3.1 Using Python's built-in sum() function, print the sum of the numbers in the list nums
print(sum(nums))

# 7.3.2 Using Python's built-in min() function, print the minimum of the numbers in the list nums
print(min(nums))

# 7.3.3 Using Python's built-in abs() function, print the absolute value of -6.
print(abs(-6))

# 7.3.4 Using Python's built-in round() function, round the number 4.67888 to two decimal places.
print(round(4.67888, 2))

# 7.4 Python Modules

# 7.4.1 Create a python module mod.
# In mod.py, create a function psum(number1, number2) that takes two arguments and prints the sum of them.
# Assume the input arguments to be numbers.
# In mod.py, create a function pmultiply(number1, number2) that takes two arguments and prints the product of them.
# Assume the input arguments to be numbers.

# mod.py
def psum(number1, number2):
   print(number1 + number2)

def pmultiply(number1, number2):
    print(number1 * number2)

# 7.4.2 Create python file main.py and import the module mod.
# In main.py run the psum() and pmultiply() functions from the module mod using any two numbers.

main.py
 from mod import psum, pmultiply
 psum(3, 4)
 pmultiply(3, 4)

# 7.4.3 In main.py, also import Python's built-in module platform.
# Then list the functions and variables in the platform module using the dir() function.
import platform
print(dir(platform))